# Generated by Django 5.2.6 on 2025-10-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único da variável (ex: area_total, quartos, padrao)', max_length=50, unique=True, verbose_name='código')),
                ('name', models.CharField(help_text='Nome descritivo da variável', max_length=200, verbose_name='nome')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da variável e como coletá-la', verbose_name='descrição')),
                ('data_type', models.CharField(choices=[('quantitativa', 'Quantitativa (Numérica)'), ('qualitativa_ordinal', 'Qualitativa Ordinal (Categorias Ordenadas)'), ('qualitativa_nominal', 'Qualitativa Nominal (Categorias)')], help_text='Tipo de variável para análise estatística', max_length=25, verbose_name='tipo de dado')),
                ('unit', models.CharField(blank=True, help_text='Unidade de medida (m², anos, km, R$, etc.)', max_length=20, verbose_name='unidade')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, help_text='Valor mínimo permitido (para quantitativas)', max_digits=15, null=True, verbose_name='valor mínimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, help_text='Valor máximo permitido (para quantitativas)', max_digits=15, null=True, verbose_name='valor máximo')),
                ('choices', models.JSONField(blank=True, help_text='Opções para variáveis qualitativas (JSON: {"codigo": "descrição", ...})', null=True, verbose_name='opções')),
                ('choice_order', models.JSONField(blank=True, help_text='Ordem das opções para variáveis ordinais (JSON: ["codigo1", "codigo2", ...])', null=True, verbose_name='ordem das opções')),
                ('is_required', models.BooleanField(default=False, help_text='Se marcado, esta variável deve ser preenchida para todos os dados', verbose_name='obrigatória')),
                ('is_active', models.BooleanField(default=True, help_text='Se desmarcado, a variável não aparece para seleção', verbose_name='ativa')),
                ('category', models.CharField(blank=True, choices=[('dimensoes', 'Dimensões e Áreas'), ('localizacao', 'Localização'), ('caracteristicas', 'Características Construtivas'), ('infraestrutura', 'Infraestrutura'), ('conservacao', 'Estado de Conservação'), ('economicas', 'Características Econômicas'), ('outras', 'Outras')], help_text='Categoria para organização', max_length=50, verbose_name='categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'variável',
                'verbose_name_plural': 'variáveis',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['code'], name='models_vari_code_3e38d1_idx'), models.Index(fields=['data_type', 'is_active'], name='models_vari_data_ty_efd000_idx'), models.Index(fields=['category'], name='models_vari_categor_1081f4_idx')],
            },
        ),
    ]
