version: '3.8'

services:
  db:
    image: postgres:15
    container_name: property_valuation_db
    environment:
      POSTGRES_DB: property_valuation
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_user -d property_valuation"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: