# Generated by Django 5.2.6 on 2025-10-29 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0, help_text='Ordem em que esta variável aparece nos formulários', verbose_name='ordem de exibição')),
                ('use_in_regression', models.BooleanField(default=True, help_text='Se esta variável deve ser considerada nos modelos de regressão', verbose_name='usar em regressão')),
                ('transformation_rule', models.TextField(blank=True, help_text='Como esta variável é calculada/transformada (ex: "log(area)", "1 se padrao=Alto, 0 caso contrário")', verbose_name='regra de transformação')),
                ('code', models.CharField(help_text='Código único da variável (ex: area_total, quartos, padrao)', max_length=50, unique=True, verbose_name='código')),
                ('name', models.CharField(help_text='Nome descritivo da variável', max_length=200, verbose_name='nome')),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada da variável e como coletá-la', verbose_name='descrição')),
                ('data_type', models.CharField(choices=[('quantitativa', 'Quantitativa (Numérica)'), ('qualitativa_ordinal', 'Qualitativa Ordinal (Categorias Ordenadas)'), ('qualitativa_nominal', 'Qualitativa Nominal (Categorias)')], help_text='Tipo de variável para análise estatística', max_length=25, verbose_name='tipo de dado')),
                ('unit', models.CharField(blank=True, help_text='Unidade de medida (m², anos, km, R$, etc.)', max_length=20, verbose_name='unidade')),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, help_text='Valor mínimo permitido (para quantitativas)', max_digits=15, null=True, verbose_name='valor mínimo')),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, help_text='Valor máximo permitido (para quantitativas)', max_digits=15, null=True, verbose_name='valor máximo')),
                ('choices', models.JSONField(blank=True, help_text='Opções para variáveis qualitativas (JSON: {"codigo": "descrição", ...})', null=True, verbose_name='opções')),
                ('choice_order', models.JSONField(blank=True, help_text='Ordem das opções para variáveis ordinais (JSON: ["codigo1", "codigo2", ...])', null=True, verbose_name='ordem das opções')),
                ('is_required', models.BooleanField(default=False, help_text='Se marcado, esta variável deve ser preenchida para todos os dados', verbose_name='obrigatória')),
                ('is_active', models.BooleanField(default=True, help_text='Se desmarcado, a variável não aparece para seleção', verbose_name='ativa')),
                ('category', models.CharField(blank=True, choices=[('dimensoes', 'Dimensões e Áreas'), ('localizacao', 'Localização'), ('caracteristicas', 'Características Construtivas'), ('infraestrutura', 'Infraestrutura'), ('conservacao', 'Estado de Conservação'), ('economicas', 'Características Econômicas'), ('outras', 'Outras')], help_text='Categoria para organização', max_length=50, verbose_name='categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('parent_variable', models.ForeignKey(blank=True, help_text='Para variáveis dicotômicas: qual variável categórica originou esta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_variables', to='properties.variable', verbose_name='variável origem')),
            ],
            options={
                'verbose_name': 'variável',
                'verbose_name_plural': 'variáveis',
                'ordering': ['category', 'display_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='properties__code_0942d3_idx'), models.Index(fields=['category', 'is_active'], name='properties__categor_bba7cb_idx')],
            },
        ),
    ]
